# All sections are optional except [printers]
# The SMTP section even if not used is validated, comment out if not using

[smtp]
# SMTP Server to send emails with
host = "smtp.domain.com"
port = 587
encryption = "starttls" # or "tls" or "none"
user = "" # Also used for the 'from' field
password = ""

# You can specify where to send specific notifications to specific destinations.
# Comment out a section if you do not want notifications, or leave empty lists
# Notifications types:
# - notifications.on_done
#
# Note: Webhooks are currently designed for discord compatibility only

#[notifications.on_done]
#emails = ["your@email.com"]
#webhooks = ["https://discord.com/webhook-url-here"]

[general]
# An optional password required to be used for any API that writes data / changes something.
# If blank or missing, all printers will be read-only
write_password = "...."

[printers]
# All printers the api uses, this will be listed in /api/printers. The key is the friendly name of printer
# Fields:
#   ip - ip address of printer, without port (port defaults to 8899)
main = { ip = "192.168.1.89" }