# All sections are optional except [printers]
# The SMTP section even if not used is validated, comment out if not using

[smtp]
# SMTP Server to send emails with
host = "smtp.domain.com"
port = 587
encryption = "starttls" # or "tls" or "none"
user = "" # Also used for the 'from' field
password = ""

# You can specify where to send specific notifications to specific destinations.
# Comment out a section if you do not want notifications, or leave empty lists
# Notifications types:
# - notifications.on_done
#
# Note: Webhooks are currently designed for discord compatibility only

#[notifications.on_done]
#emails = ["your@email.com"]
#webhooks = ["https://discord.com/webhook-url-here"]

[auth]
# By default API allows anyone to read or change settings on the printer. This includes setting temperature, moving, starting, cancelling print, etc
# An optional password can be configured to control access

# If either password_for is set to true, the password must be provided as a "x-secret" header

# Is password needed for write access (set temperature, move, etc.)
password_for_write = false
# Is password needed for read access (any printer API)
password_for_read = false
# If password is blank, then no entered password will be accepted if a password is required
password = "test"

[printers]
# All printers the api uses, this will be listed in /api/printers. The key is the friendly name of printer
# Fields:
#   ip - ip address of printer, without port (port defaults to 8899)
main = { ip = "192.168.1.89" }